development:
  secret_key_base: abcdefghijklmnopqrstuvwxyz1234567890
 
test:
  secret_key_base: abcdefghijklmnopqrstuvwxyz1234567890
 
quality:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
